# Generated by Django 2.1.7 on 2019-04-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20190401_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_admin',
        ),
    ]
