# Generated by Django 2.2 on 2019-04-07 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20190401_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='register_time',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='register_time',
        ),
    ]
