# Generated by Django 2.2 on 2019-05-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20190505_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_num',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='course',
            name='select_num',
            field=models.IntegerField(default=0),
        ),
    ]
