# Generated by Django 2.2 on 2019-04-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=30)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
