# Generated by Django 2.2 on 2019-04-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_camera_is_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='is_phone',
            field=models.BooleanField(default=False),
        ),
    ]
