# Generated by Django 2.2 on 2019-04-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20190409_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='camera_id',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
