# Generated by Django 2.2 on 2019-04-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='camera_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
