# Generated by Django 2.2 on 2019-04-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20190410_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url_processed',
            field=models.CharField(default='', max_length=200),
        ),
    ]
