# Generated by Django 2.2 on 2019-05-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_photo_url_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
