# Generated by Django 2.2 on 2019-05-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_detection_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='photo_quality',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
