# Generated by Django 2.2 on 2019-05-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20190508_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='is_phone',
            field=models.BooleanField(),
        ),
    ]
