# Generated by Django 2.2 on 2019-05-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_auto_20190508_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_phone',
        ),
    ]
