# Generated by Django 2.2 on 2019-05-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_photo_camera_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('is_auto_detecting', models.BooleanField(default=False)),
                ('is_auto_predicting', models.BooleanField(default=False)),
                ('detection_model', models.CharField(default='RetinaNet', max_length=30)),
                ('detection_speed', models.CharField(default='normal', max_length=30)),
                ('prediction_model', models.CharField(default='SqueezeNet', max_length=30)),
                ('prediction_speed', models.CharField(default='normal', max_length=30)),
            ],
        ),
    ]
