# Generated by Django 2.2 on 2019-05-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0022_auto_20190508_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='detection_speed',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='photo',
            name='prediction_speed',
            field=models.CharField(default='', max_length=30),
        ),
    ]
